---
billingDeptId: "90522"
project:
  name: kohls-etcc-tax-prd
  managed: true
  folderId: "155882274299"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90522"
    project-manager: meenakshi-sathyavageeswaran
    devops-lead: austin-paul
    environment-type: prd
    line-of-business: etcc
    project-requestor: austin-paul
    app-name: tax-services
