---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-operator-cluster-admin
  namespace: "kcc-seed"
subjects:
- kind: ServiceAccount
  name: "eunomia-runner-cluster-admin"
  namespace: "kcc-seed"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
