I. Create a ConfigMap and a pod that will utilize it:

kubectl create configmap doms-configmap --from-literal=owner=dom

nano yourname-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
spec:
  containers:
    - name: nginx-configmap
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: OWNER
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: doms-configmap
              # Specify the key associated with the value
              key: owner

kubectl apply -f yourname-pod.yaml


II. Create a Secret for DB and a pod using the username and password: