---
billingDeptId: 90522
projectSharing:
  - kohls-etcc-tax-prd
  - kohls-eta-credit-prd
project:
  name: kohls-eta-xpn-prd
  managed: true
  deletionProtect: true
  folderId: "970875009337"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90522
    project-manager: ron-minue
    devops-lead: placeholder
    environment-type: prd
    line-of-business: eta
    project-requestor: ron-minue
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  networkmanagement.googleapis.com:
