---
project:
  name: doms-scf-prd
  managed: true
  deletionProtect: true
  folderId: "1038729868631"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90569"
    project-manager: matt-arnold
    devops-lead: todd-winter
    environment-type: prd
    line-of-business: ocf
    project-requestor: neha-racharla
serviceAPIs:
   cloudfunctions.googleapis.com:
   cloudapis.googleapis.com:
   cloudscheduler.googleapis.com:
   monitoring.googleapis.com:
   pubsub.googleapis.com:
   cloudbuild.googleapis.com:
   cloudresourcemanager.googleapis.com:
   secretmanager.googleapis.com:
