---
billingDeptId: "90513"
project:
  name: doms-sec-xpn-lle
  managed: true
  folderId: "778811484176"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90513"
    project-manager: kelly-neumann
    devops-lead: richard-holcombe
    environment-type: lle
    line-of-business: cpe
    project-requestor: thomas-wesolowski
serviceAPIs:
  compute.googleapis.com:
  oslogin.googleapis.com:
  cloudresourcemanager.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
  container.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
projectSharing:
- doms-sec-engineering-lle
#- doms-sec-bastion-lle
- doms-sec-oasa-lle
- doms-sec-vault-lle
- doms-sec-okta-lle
