---
billingDeptId: "90586"
project:
  name: kohls-rapidpaas-sbx
  managed: true
  folderId: "345254712059"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: nolan-hansen
    devops-lead: ford-donald
    environment-type: sbx
    line-of-business: cpe
    project-requestor: nolan-hansen
serviceAPIs:
  cloudapis.googleapis.com:
  cloudresourcemanager.googleapis.com:
  compute.googleapis.com:
  container.googleapis.com:
  dns.googleapis.com:
  firebase.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
