---
billingDeptId: "90528"
project:
  name: kohls-infra-kdx-prd
  managed: true
  deletionProtect: true
  folderId: "980929416788"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90528"
    project-requestor: tim-smith
    project-manager: tim-smith
    devops-lead: bill-mitchell
    line-of-business: infra
    environment-type: prd
serviceAPIs:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  compute.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
