---
billingDeptId: 90585
project:
  name: kohls-bda-xpn-prd
  managed: true
  deletionProtect: true
  folderId: "970875009337"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90585
    project-manager: eric-cherveny
    devops-lead: ramkishore-modukur
    environment-type: prd
    line-of-business: bda
    project-requestor: larry-mcmahon
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
projectSharing:
- kohls-bda-prd
- kohls-bda-mkt-prd
