---
billingDeptId: "90514"
project:
  name: doms-merch-xpn-lle
  managed: true
  deletionProtect: true
  folderId: "778811484176"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90514"
    project-manager: joel-schrock
    devops-lead: griffin-strain
    environment-type: lle
    line-of-business: merch
    project-requestor: joel-schrock
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  compute.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  storage-api.googleapis.com:
projectSharing:
- doms-merch-pl-lle
- doms-merch-item-lle
- doms-merch-in-lle
- doms-merch-ps-lle
