---
billingDeptId: "90565"
project:
  name: doms-cx-poc-lle
  deletionProtect: true
  managed: true
  folderId: "124759181101"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90565"
    project-manager: ravi
    devops-lead: manish
    environment-type: lle
    line-of-business: cx
    project-requestor: manish

serviceAPIs:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
