---
billingDeptId: "90522"

project:
  name: kohls-etcc-tax-lle
  managed: true
  folderId: "859213288423"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90522"
    project-manager: meenakshi-sathyavageeswaran
    devops-lead: austin-paul
    environment-type: lle
    line-of-business: etcc
    project-requestor: austin-paul
    app-name: tax-services
