---
billingDeptId: "90507"

project:
  name: kohls-etcc-exterro-prd
  managed: true
  folderId: "155882274299"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  #
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90507"
    project-manager: ernie-evangelista
    devops-lead: fred-parham
    environment-type: prd
    line-of-business: etcc
    project-requestor: mackenzie-peters
    app-name: exterro
serviceAPIs:
  vault.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  admin.googleapis.com:
  gmail.googleapis.com:
  tasks.googleapis.com:
  contacts.googleapis.com:
