---
billingDeptId: "90586"
project:
  name: domsdev-inp-demofix-02
  managed: true
  folderId: "922938220950"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: michael-halbachs
    devops-lead: michael-halbachs
    environment-type: dev
    line-of-business: michael-halbachs
    project-requestor: michael-halbachs
