---
project:
  name: doms-scf-lle
  managed: true
  deletionProtect: true
  folderId: "1031310294968"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90577"
    project-manager: matt-arnold
    devops-lead: todd-winter
    environment-type: lle
    line-of-business: ocf
    project-requestor: neha-racharla
serviceAPIs:
  cloudfunctions.googleapis.com:
  cloudapis.googleapis.com:
  cloudscheduler.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  cloudbuild.googleapis.com:
  cloudresourcemanager.googleapis.com:
  secretmanager.googleapis.com:
