---
billingDeptId: 90565
project:
  name: doms-cx-xpn-lle
  managed: true
  deletionProtect: true
  folderId: "402839726008"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90565"
    project-manager: ravi
    devops-lead: placeholder
    environment-type: lle
    line-of-business: cx
    project-requestor: manish
projectSharing:
- doms-bda-dse-lle
- doms-cce-dbaas-lle
- doms-cce-openshift-lle
- doms-cx-associate-lle
- doms-cx-loyalty-retailsrv-lle
- doms-cx-pci-lle
- doms-cx-poc-lle
- doms-cx-post-purchase-lle
- doms-cx-rtl-lle
- doms-cx-shop-lle
- doms-cx-sre-lle
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  container.googleapis.com:
  oslogin.googleapis.com:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networktopology.googleapis.com:
  servicenetworking.googleapis.com:
