apiVersion: v1
kind: ConfigMap
metadata:  
  name: l5-coredns  
  namespace: kube-system 
data:
  example.server: | # All custom server files must have a “.server” file extension. 
    # Change example.com to the domain you wish to forward.
    example.com {
      # Change 8.8.8.8 (Google) to your DNS resolver.
      forward . 8.8.8.8
    }
