apiVersion: apps/v1
kind: Deployment
metadata:
  name: l6-pod
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: l6-pod
        image: redis
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
    
