apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
   strategy:
      rollingUpdate:
         maxSurge: 50%
         maxUnavailable: 50%
   template:
      spec:
         containers:
            - name: nginx
              image: nginx:1.19.6
              ports:
                 - containerPort: 80
