---
billingDeptId: 90528
project:
  name: kohls-iaas-xpn-lle
  managed: true
  deletionProtect: true
  folderId: 778811484176
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90528
    project-manager: keith-halverson
    devops-lead: russ-nell
    environment-type: lle
    line-of-business: iaas
    project-requestor: bryon-matthews
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
