---
billingDeptId: "90548"
project:
  name: kohls-iaas-prd
  managed: false
  folderId: "206335353876"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90548"
    devops-lead: jacob-napp
    environment-type: prd
    line-of-business: iaas
    project-manager: josh-doll
    project-requestor: hamilton-hoover
