---
billingDeptId: 90548
project:
  name: kohls-platformops-xpn-lle
  managed: true
  deletionProtect: true
  folderId: 778811484176
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90548
    project-manager: byron-mathews
    devops-lead: mark-luther
    environment-type: lle
    line-of-business: platform
    project-requestor: sean-malloy
serviceAPIs:
  compute.googleapis.com:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  servicenetworking.googleapis.com:

projectSharing:
- kohls-platform-dbaas-ops
- kohls-platform-maas-ops
- kohls-platform-openshift-ops
- kohls-platform-netservices-lle
