Answer the following:
Define RBAC.
What are the four objects of RBAC?
List the 3 elements of RBAC.
How are roles and cluster roles different?

Addtional Reading:

https://kubernetes.io/blog/2017/04/rbac-support-in-kubernetes/
https://kubernetes.io/docs/reference/access-authn-authz/rbac/
https://www.cncf.io/blog/2018/08/01/demystifying-rbac-in-kubernetes/
