---
project:
  name: doms-cpe-e2edemo-lle
  deletionProtect: false
  managed: true
  folderId: "53524313723"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels: # Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed as characters in labels
    billing-dept-id: "90586"
    project-manager: charles-anthony
    devops-lead: mark-doll
    environment-type: lle
    project-requestor: steve-pethan
    line-of-business: cpe
