---
project:
  name: doms-ocf-stateful-lle
  managed: false
  folderId: "1031310294968"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90569"
    project-manager: abhilasha-jain
    devops-lead: placeholder
    environment-type: lle
    line-of-business: ocf
    lob: ocf
    project-requestor: aparna-deshpande
