---
billingDeptId: "90586"
project:
  name: kohlsdev-jeremy-schema-va-01
  managed: true
  folderId: "4553252134"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: michael-halbach
    devops-lead: michael-halbach
    environment-type: dev
    line-of-business: michael-halbach
    project-requestor: michael-halbach
serviceAPIs:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  compute.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  oslogin.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
