---
billingDeptId: 90528
project:
  name: kohls-infra-xpn-lle
  managed: true
  deletionProtect: true
  folderId: 711959037663
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90528
    project-manager: tim-smith
    devops-lead: placeholder
    environment-type: lle
    line-of-business: infra
    project-requestor: tim-smith
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  container.googleapis.com:
  oslogin.googleapis.com:
  networkmanagement.googleapis.com:

projectSharing:
- kohls-infra-aiops-lle
- kohls-infra-monitoring-lle
- kohls-infra-kdx-lle
- kohls-infra-pie-lle
