pylint:
  stage: data-validation
  image: registry.gitlab.com/pipeline-components/pylint:edge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  needs: []
  script:
    - pylint --version
    - pylint --min-similarity-lines=50 --disable=R0801 --generate-rcfile
    - if [ $(find . -type f -name '*.py' | wc -l) -ne 0 ]; then find . -type f -name '*.py' | xargs pylint -v --fail-under=8.5; fi
