---
billingDeptId: "90528"
project:
  name: doms-infra-vmo-prd
  deletionProtect: true
  managed: true
  folderId: "980929416788"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90528"
    project-manager: moira-lechtenberg
    devops-lead: lindsay-colonna
    environment-type: prd
    line-of-business: infra
    project-requestor: joseph-lavoy
    business: vmo
serviceAPIs:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
