---
project:
  labels:
    billing-dept-id: '90576'
    environment-type: lle
    devops-lead: joseph-van-horn
    project-manager: manasa-ramayanam
    line-of-business: sec
    project-requestor: thomas-wesolowski
  name: kohls-sec-bastion-lle
  managed: true
  deleteProtect: true
  folderId: "882166644980"
  billingAccount: 00C36A-CD0BDB-E543D0
# For lookup table of line of business codes: https://gitlab.com/kohls/infra/platform_enablement/cloud-config/gcp-config/-/blob/main/docs/Projects/Project_Jump_Start_Guide.md#netx-project-folder-id-lookup-table
