---
project:
  name: kohls-ocf-prd
  managed: true
  deletionProtect: true
  folderId: 48229324135
  billingAccount: 00C36A-CD0BDB-E543D0
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: '90577'
    environment-type: prd
    devops-lead: todd-winter
    project-manager: matt-arnold
    line-of-business: ocf
    project-requestor: neha-racharla
serviceAPIs:
   cloudfunctions.googleapis.com:
   cloudapis.googleapis.com:
   cloudscheduler.googleapis.com:
   monitoring.googleapis.com:
   pubsub.googleapis.com:
   cloudbuild.googleapis.com:
   cloudresourcemanager.googleapis.com:
   secretmanager.googleapis.com:
