---
billingDeptId: "90548"
project:
  name: doms-platform-dbaas-prd
  deletionProtect: true
  managed: true
  folderId: "106220115873"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90548"
    project-manager: marsha-siatczynski
    devops-lead: ryan-criss
    environment-type: prd
    line-of-business: cpe
    project-requestor: ryan-criss
serviceAPIs:
  cloudasset.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  container.googleapis.com:
  containerregistry.googleapis.com:
  datamigration.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
  oslogin.googleapis.com:
  pubsub.googleapis.com:
  redis.googleapis.com:
  servicenetworking.googleapis.com:
  sqladmin.googleapis.com:
  sql-component.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
