project:
  name: kohls-cx-loyalty-retailsrv-lle
  managed: true
  folderId: "124759181101" # CCX
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90565"
    project-manager: "mike-bohn"
    devops-lead: "kiran-mothekani"
    environment-type: lle
    line-of-business: loyalty-retailservices
    lob: loyalty-retailservices
    project-requestor: "manish-parmar"

serviceAPIs:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
