---
billingDeptId: "90548"
project:
  name: doms-platform-netservices-lle
  managed: true
  folderId: "53524313723"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90548"
    project-manager: josh-doll
    devops-lead: tyler-welnak
    environment-type: lle
    line-of-business: platform
    project-requestor: james-barber
serviceAPIs:
  compute.googleapis.com:
  oslogin.googleapis.com:
  cloudresourcemanager.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
  deploymentmanager.googleapis.com:
