---
billingDeptId: "90514"
project:
  name: kohls-merch-ps-prd
  managed: true
  folderId: "217021366087"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90514"
    project-manager: ben-klink
    devops-lead: aaron-wolmutt
    environment-type: prd
    line-of-business: ps
    project-requestor: aaron-wolmutt
