---
project:
  name: doms-devexp-tools-prd
  managed: true
  folderId: "980929416788"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: will_white
    devops-lead: christian_madrigal
    environment-type: prd
    line-of-business: cpe
    project-requestor: russell_nell
serviceAPIs:
  compute.googleapis.com:
  pubsub.googleapis.com:
