---
billingDeptId: "90538"
project:
  name: kohls-etcc-aacs-prd
  deletionProtect: true
  managed: true
  folderId: "155882274299"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90538"
    project-manager: carlson-quick
    devops-lead: mark-battaglia
    environment-type: prd
    line-of-business: etcc
    project-requestor: mohammad-firdausi
serviceAPIs:
  bigquery.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
