project:
  name: doms-cx-shop-prd
  managed: true
  folderId: "121961327479" # CCX
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90565"
    project-manager: "james-ryan"
    devops-lead: "joshy-madhavan"
    environment-type: prd
    line-of-business: shop
    lob: shop
    project-requestor: "manish-parmar"

serviceAPIs:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
