---
billingDeptId: "90586"
project:
  name: doms-cpe-sre-prd
  managed: true
  folderId: "980929416788"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: steve_pethan
    devops-lead: peter_kostyukov
    environment-type: prd
    line-of-business: cpe
    project-requestor: vijay_selvamani
serviceAPIs:
  bigquery.googleapis.com:
  compute.googleapis.com:
  cloudresourcemanager.googleapis.com:
  iam.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  stackdriver.googleapis.com:
