---
project:
  name: doms-ocf-lle
  managed: true
  deletionProtect: true
  folderId: 1057338141298
  billingAccount: 00C36A-CD0BDB-E543D0
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: '90577'
    environment-type: lle
    devops-lead: undefined
    project-manager: abhilasha-jain
    line-of-business: ocf
    project-requestor: aparna-deshpande
serviceAPIs:
  cloudfunctions.googleapis.com:
  cloudapis.googleapis.com:
  cloudscheduler.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  cloudbuild.googleapis.com:
  cloudresourcemanager.googleapis.com:
  secretmanager.googleapis.com:
