---
billingDeptId: "90514"
project:
  name: kohls-merch-pd-lle
  managed: true
  folderId: "963520663007"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90514"
    project-manager: lee-davies
    devops-lead: robert-colyard-jr
    environment-type: lle
    line-of-business: product-development
    project-requestor: lee-davies
serviceAPIs:
  cloudapis.googleapis.com:
  pubsub.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  compute.googleapis.com:
  dns.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
