---
project:
  name: kohlsdev-jeremy-bill-02
  managed: true
  folderId: "922938220950"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels: # Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed as characters in labels
    billing-dept-id: "90586"
    project-manager: josh-doll
    devops-lead: mark-doll
    environment-type: lle
    env: inspec-test
    just-another-label: test-sample-label
