---
billingDeptId: "90505"
project:
  name: kohls-ecom-tvs-corp-lle
  deletionProtect: true
  managed: false
  folderId: "872364499101"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90505"
    project-manager: matt-scholtka
    devops-lead: kiran-mothekani
    environment-type: lle
    line-of-business: cpe
    project-requestor: kiran-mothekani
