---
project:
  name: doms-bda-prd
  managed: true
  folderId: "1064417150642" # merch-mkt-analytics
  billingAccount: 00C36A-CD0BDB-E543D0
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90585"
    project-manager: "eric-cherveny"
    devops-lead: "ananth-bilakanti"
    environment-type: prd
    line-of-business: dp
    lob: dp
    project-requestor: "jasvinder-singh"
