---
billingDeptId: 90528
project:
  name: kohls-infra-xpn-prd
  managed: true
  deletionProtect: true
  folderId: 46233836581
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90528
    project-manager: tim-smith
    devops-lead: placeholder
    environment-type: prd
    line-of-business: infra
    project-requestor: tim-smith
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  container.googleapis.com:
  oslogin.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
projectSharing:
  - kohls-infra-pie-prd
  - kohls-infra-aiops-prd
  - kohls-infra-monitoring-prd
  - kohls-infra-kdx-prd
