Lesson 4 - Storage

Answer the following:

Why do we need volumes?
What is a persistent volume?
What is a persistent volume claim?
What are the three access modes and what do they allow?
What are some examples of cloud storage?
What are some examples of traditional storage?
Where does a local volume store its data?

Identify issues with the following persistent volume. What corrections need to be made?: (2 issues)

apiVersion: v1
kind: PersistentVolume
metadata:
  name: yourname-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 

Additonal Reading:

https://kubernetes.io/docs/concepts/storage/storage-classes/
https://itnext.io/how-to-use-custom-storage-classes-in-kubernetes-edc568acfdfe
https://kubernetes.io/docs/concepts/storage/persistent-volumes/
https://phoenixnap.com/kb/kubernetes-persistent-volumes
https://portworx.com/tutorial-kubernetes-persistent-volumes/git


