---
billingDeptId: "90522"
project:
  name: doms-eta-credit-lle
  deletionProtect: true
  managed: true
  folderId: "859213288423"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90522"
    project-manager: nicki-kaszuba
    devops-lead: nilab-mousa
    environment-type: lle
    line-of-business: eta
    project-requestor: nilab-mousa
