---
billingDeptId: "90548"
project:
  name: doms-platform-xpn-lle
  managed: true
  folderId: "778811484176"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90548"
    project-manager: marsha-siatczynski
    devops-lead: ryan-criss
    environment-type: lle
    line-of-business: platform
    project-requestor: ryan-criss
serviceAPIs:
  compute.googleapis.com:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  oslogin.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  servicenetworking.googleapis.com:
  firewallinsights.googleapis.com:

projectSharing:
- doms-platform-dbaas-lle
- doms-platform-dbaas-ops
- doms-platform-maas-lle
- doms-platform-maas-ops
- doms-platform-openshift-ops
- doms-platform-openshift-lle
- doms-platform-netservices-lle
