---
billingDeptId: "90514"
project:
  name: doms-merch-in-lle
  managed: true
  folderId: "963520663007"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90514"
    project-manager: "susmita_agnihotri"
    devops-lead: "gordon_reitz"
    environment-type: "lle"
    line-of-business: "in"
    project-requestor: "susmita_agnihotri"
serviceAPIs:
  aiplatform.googleapis.com:
  automl.googleapis.com:
  bigquery.googleapis.com:
  bigqueryconnection.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  cloudbuild.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudscheduler.googleapis.com:
  cloudtasks.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  container.googleapis.com:
  containerregistry.googleapis.com:
  dataflow.googleapis.com:
  dataproc.googleapis.com:
  datastore.googleapis.com:
  deploymentmanager.googleapis.com:
  dialogflow.googleapis.com:
  dns.googleapis.com:
  firebaserules.googleapis.com:
  firestore.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  iap.googleapis.com:
  language.googleapis.com:
  logging.googleapis.com:
  ml.googleapis.com:
  monitoring.googleapis.com:
  notebooks.googleapis.com:
  oslogin.googleapis.com:
  pubsub.googleapis.com:
  redis.googleapis.com:
  replicapool.googleapis.com:
  replicapoolupdater.googleapis.com:
  resourceviews.googleapis.com:
  run.googleapis.com:
  servicenetworking.googleapis.com:
  sourcerepo.googleapis.com:
  spanner.googleapis.com:
  sqladmin.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  translate.googleapis.com:
  vision.googleapis.com:
