---
billingDeptId: "90586"
project:
  name: doms-platform-openshift-prd
  managed: true
  folderId: "48229324135"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: steve-pethan
    devops-lead: nicholas-sanborn
    environment-type: prd
    line-of-business: cpe
    project-requestor: sean-malloy
serviceAPIs:
  cloudapis.googleapis.com:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  computescanning.googleapis.com:
  containeranalysis.googleapis.com:
  containerregistry.googleapis.com:
  dns.googleapis.com:
  file.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  iap.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  networksecurity.googleapis.com:
  osconfig.googleapis.com:
  oslogin.googleapis.com:
  replicapool.googleapis.com:
  resourceviews.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
