---
billingDeptId: "90586"

project:
  environmentType: ops
  lineOfBusiness: infra
  projectName: doms-cpedemo-xpn-lle-01
  managed: true
  folderId: "144994841496"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    devopsLead: me
    env: lle-01
    environmentType: lle
    projectManager: me

serviceAPIs:
- cloudresourcemanager.googleapis.com
- storage-api.googleapis.com
- storage-component.googleapis.com
- stackdriver.googleapis.com
- compute.googleapis.com
- container.googleapis.com

projectSharing:         # List of Project Names
