project:
  name: kohls-cx-associate-prd
  managed: true
  folderId: "121961327479" # CCX
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: "90526"
    project-manager: "corinne-dubois"
    devops-lead: "umar-farook"
    environment-type: prd
    line-of-business: associate
    lob: associate
    project-requestor: "umar-farook"
serviceAPIs:
  bigquery.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  cloudapis.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  containerregistry.googleapis.com:
  dataflow.googleapis.com:
  datastore.googleapis.com:
  deploymentmanager.googleapis.com:
  dns.googleapis.com:
  firebase.googleapis.com:
  firestore.googleapis.com:
  googlecloudmessaging.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  replicapool.googleapis.com:
  resourceviews.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
