---
project:
  name: doms-credit-ia-lle
  managed: true
  folderId: "884280016542"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90510"
    project-manager: judy-gilbert
    devops-lead: shruti-goel
    environment-type: lle
    line-of-business: marketing
    project-requestor: thomas-erdahl
