---
billingDeptId: "90577"
project:
  name: doms-cx-scf-instaclustr-lle
  managed: true
  folderId: "124759181101"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90577"
    project-manager: matt-arnold
    devops-lead: todd-winter
    environment-type: lle
    line-of-business: ocf
    project-requestor: todd-winter
