---
billingDeptId: "90514"
project:
  name: doms-merch-sre-lle
  managed: true
  folderId: "963520663007"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90514"
    project-manager: darlene-thadison
    devops-lead: craig-kehoe
    environment-type: lle
    line-of-business: sre
    project-requestor: craig-kehoe
  serviceAPIs:
    cloudfunctions.googleapis.com:
