---
billingDeptId: "90586"
projectSharing:
- doms-cpe-image-mgmt-prd
- doms-devexp-tools-prd
- doms-cpe-sre-prd
project:
  name: doms-cpe-xpn-prd
  managed: false
  folderId: "970875009337"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_),lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: charles-anthony
    devops-lead: placeholder
    environment-type: prd
    line-of-business: cpe
    project-requestor: charles-anthony

serviceAPIs:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
