---
billingDeptId: "90565"
project:
  name: doms-cce-openshift-lle
  managed: true
  folderId: "124759181101"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90565"
    project-manager: william-white
    devops-lead: nicholas-sanborn
    environment-type: lle
    line-of-business: cce
    project-requestor: vincent-sabatini
serviceAPIs:
  cloudapis.googleapis.com:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  containeranalysis.googleapis.com:
  containerregistry.googleapis.com:
  dns.googleapis.com:
  file.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  iap.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  networksecurity.googleapis.com:
  osconfig.googleapis.com:
  oslogin.googleapis.com:
  replicapool.googleapis.com:
  resourceviews.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:

