---
project:
  name: kohls-iaas-lle
  managed: true
  folderId: "557759831541"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90546"
    project-manager: josh_doll
    devops-lead: hamilton_hoover
    environment-type: lle
    line-of-business: cpe
    project-requestor: russell_nell
# Loaded in all the API's currently enabled, not all are actually being used
serviceAPIs:
  #admin.googleapis.com:
  #appengine.googleapis.com:
  bigquery.googleapis.com:
  bigqueryconnection.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  bigtable.googleapis.com:
  bigtableadmin.googleapis.com:
  cloudasset.googleapis.com:
  cloudbilling.googleapis.com:
  cloudbuild.googleapis.com:
  cloudfunctions.googleapis.com:
  #cloudkms.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudscheduler.googleapis.com:
  #cloudtrace.googleapis.com:
  #composer.googleapis.com:
  compute.googleapis.com:
  #container.googleapis.com:
  #containeranalysis.googleapis.com:
  containerregistry.googleapis.com:
  #containerscanning.googleapis.com:
  datastore.googleapis.com:
  deploymentmanager.googleapis.com:
  #dlp.googleapis.com:
  dns.googleapis.com:
  #drive.googleapis.com:
  #endpointsportal.googleapis.com:
  fcm.googleapis.com:
  #firebaserules.googleapis.com:
  firestore.googleapis.com:
  #groupssettings.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  #iap.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  #oslogin.googleapis.com:
  pubsub.googleapis.com:
  recommender.googleapis.com:
  #redis.googleapis.com:
  replicapool.googleapis.com:
  #replicapoolupdater.googleapis.com:
  resourceviews.googleapis.com:
  run.googleapis.com:
  #securitycenter.googleapis.com:
  servicemanagement.googleapis.com:
  #servicenetworking.googleapis.com:
  #source.googleapis.com:
  spanner.googleapis.com:
  #sql-component.googleapis.com:
  #sqladmin.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  #vpcaccess.googleapis.com:
  #websecurityscanner.googleapis.com:
