---
billingDeptId: "90507"

project:
  name: kohls-etcc-finstrat-lle
  managed: true
  folderId: "859213288423"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90507"
    project-manager: emily-gries
    devops-lead: fred-parham
    environment-type: lle
    line-of-business: etcc
    project-requestor: zackary-luedtke
    app-name: finstrat-service
