---
billingDeptId: "90586"

project:
  name: doms-paas-ops
  deletionProtect: true
  managed: false
  folderId: "979004260447"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: steve-pethan
    devops-lead: heiko
    environment-type: lle
    line-of-business: paas
    project-requestor: heiko
