# Project file created using automation v 2.0
project:
  name: doms-infra-cuds-prd
  managed: true
  deletionProtect: true
  folderId: 980929416788
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    # Only hyphens (-), underscores (_) lowercase characters,
    # and numbers are allowed as characters in labels
    billing-dept-id: '90548'
    environment-type: prd
    line-of-business: infra
    project-requestor: zaki-shaikh
    project-manager: zaki-shaikh
    devops-lead: jacob-napp
serviceAPIs:
  compute.googleapis.com: null  #  default service API
  storage-api.googleapis.com: null #  default service API
  monitoring.googleapis.com: null #  default service API
  logging.googleapis.com: null #  default service API
