#I. Setup your deployment

nano yourname-service.yaml
nano yourname-pod.yaml

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

kubectl apply -f yourname-service.yaml
kubectl apply -f yourname-pod.yaml
kubectl get all

#II. Identify the pod IP addresses and DNS name of the service

Get the names and IP addresses of your pods
SSH into one of your pods
Test connectivity from your pod to another

kubectl get po -l app=nginx -o wide
kubectl exec -it <pod name> -- /bin/bash
ping <IP of destination pod>

Commands to Use:

kubectl apply -f yourname-service.yaml
kubectl apply -f yourname-pod.yaml
kubectl get all
kubectl get po -l app=nginx -o wide
kubectl exec -it <pod name> -- /bin/bash
ping <IP of destination pod>

