---
project:
  labels:
    billing-dept-id: '90513'
    environment-type: prd
    devops-lead: rich_holcombe
    project-manager: kelly_neumann
    line-of-business: sec
    project-requestor: rich_holcombe
  name: doms-sec-logging-prd
  managed: true
  deleteProtect: true
  folderId: 726913521927
  billingAccount: 00C36A-CD0BDB-E543D0
# For lookup table of line of business codes: https://gitlab.com/doms/infra/platform_enablement/cloud-config/gcp-config/-/blob/main/docs/Projects/Project_Jump_Start_Guide.md#netx-project-folder-id-lookup-table
