---
project:
  billingAccount: 00C36A-CD0BDB-E543D0
  deleteProtect: false
  folderId: 124759181101
  labels:
    billing-dept-id: '90561'
    devops-lead: hey-lead
    environment-type: lle
    line-of-business: cx
    project-manager: hey-manager
    project-requestor: hey-manager
  managed: true
  name: doms-cx-associate-new-lle
