---
billingDeptId: "90586"
project:
  name: doms-cpe-cpa-lle
  managed: false
  folderId: "872364499101"
  labels:
    environment-type: lle
    billing-dept-id: "90586"
    project-manager: josh-doll
    devops-lead: mark-doll
    line-of-business: cpe
    project-requestor: zaki
