Lesson 3 - Namespaces

Answer the following:

What is a namespace and why do we use them?
What are the 2 most popular environments developers deploy namespaces in?
What is CNC?
If I wanted to access a database from 'Namespace Prod' that resides in 'Namespace Test', what would my address look like?
What are the 3 primary namespaces and what does each one do?
What is kubens and does it come pre-installed in Kubernetes?


Identify what the following 3 commands will accomplish. Write your description below it: 


nano <yourname>-namespace.yaml

  apiVersion: v1
  kind: Namespace
  metadata:
      name: <yourname>-namespace

kubectl apply -f <yourname>-namespace.yaml

What would be a reason that you 


Identify issues with the following deployment. What corrections need to be made?: (2 issues)

nano <yourname>-pod.yam

apiVersion: v1
kind: Pod
metadata:
  name: <yourname>-pod
  namespace: <yourname>-
  labels:
    name: <yourname>-pod
spec:
  containers:
    name: <yourname>-pod
    image: nginx