---
billingDeptId: "90586"
project:
  name: kohls-cpe-cne-lle
  managed: true
  folderId: "53524313723"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: charles_anthony
    devops-lead: james_barber
    environment-type: lle
    line-of-business: cpe
    project-requestor: james_barber
serviceAPIs:
  compute.googleapis.com:
  cloudasset.googleapis.com:
  container.googleapis.com:
  cloudresourcemanager.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  oslogin.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  networktopology.googleapis.com:
