---
steps:
- name: 'gcr.io/$PROJECT_ID/graphviz-cloudbuild'
  id: 'Generate pdf for input.yml'
  entrypoint: 'sh'
  args: ['-x', '/usr/local/bin/yml2pdf.sh', 'input.yml', 'input.pdf']
artifacts:
  objects:
    location: 'gs://kohls-iaas-lle-cloud-build-artifacts/test-buids/'
    paths: ['input.pdf']
