---
project:
  name: doms-devexp-tools-sbx
  managed: true
  folderId: "345254712059"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: will_white
    devops-lead: christian_madrigal
    environment-type: sbx
    line-of-business: cpe
    project-requestor: russell_nell
serviceAPIs:
  analytics.googleapis.com:
  bigquery-json.googleapis.com:
  bigquery.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  bigtable.googleapis.com:
  cloudapis.googleapis.com:
  cloudasset.googleapis.com:
  cloudbilling.googleapis.com:
  cloudbuild.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudscheduler.googleapis.com:
  compute.googleapis.com:
  containerregistry.googleapis.com:
  dataflow.googleapis.com:
  dataproc.googleapis.com:
  datastore.googleapis.com:
  deploymentmanager.googleapis.com:
  dialogflow.googleapis.com:
  firebase.googleapis.com:
  firestore.googleapis.com:
  googlecloudmessaging.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  sheets.googleapis.com:
  spanner.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storagetransfer.googleapis.com:
  vmmigration.googleapis.com:
