---
billingDeptId: "90586"
project:
  name: kohls-cpa-xpn-lle
  managed: true
  folderId: "778811484176"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_),lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: hamilton-hoover
    devops-lead: pavel-leonovitch
    environment-type: lle
    line-of-business: cpa
    project-requestor: hamilton-hoover
serviceAPIs:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
