---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  labels:
    label-one: "value-one"
  name: mark-bucket-sample
  namespace: gcp-domsdev-cpa-inspec
spec:
  lifecycleRule:
  - action:
      type: Delete
    condition:
      age: 7
  versioning:
    enabled: false
