---
billingDeptId: "90586"
project:
  name: kohls-platform-openshift-ops
  managed: true
  folderId: "1057338141298"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: steve-pethan
    devops-lead: nicholas-sanborn
    environment-type: ops
    line-of-business: cpe
    project-requestor: vincent-sabatini
serviceAPIs:
  cloudapis.googleapis.com:
  cloudasset.googleapis.com:
  cloudresourcemanager.googleapis.com:
  cloudtrace.googleapis.com:
  compute.googleapis.com:
  computescanning.googleapis.com:
  containeranalysis.googleapis.com:
  containerregistry.googleapis.com:
  dns.googleapis.com:
  file.googleapis.com:
  iam.googleapis.com:
  iamcredentials.googleapis.com:
  iap.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  networksecurity.googleapis.com:
  osconfig.googleapis.com:
  oslogin.googleapis.com:
  replicapool.googleapis.com:
  resourceviews.googleapis.com:
  servicemanagement.googleapis.com:
  serviceusage.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  # only reuqired in ops
  bigquery.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  cloudbuild.googleapis.com:
  cloudfunctions.googleapis.com:
  cloudkms.googleapis.com:
  cloudscheduler.googleapis.com:
  container.googleapis.com:
  deploymentmanager.googleapis.com:
  pubsub.googleapis.com:
