---
billingDeptId: "90522"
project:
  name: kohls-etcc-payments-lle
  managed: true
  folderId: "859213288423"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90522"
    project-manager: siew-leng-lim
    devops-lead: omair-chughtai
    environment-type: lle
    line-of-business: etcc
    project-requestor: omair-chughtai
serviceAPIs:
  compute.googleapis.com:
  cloudresourcemanager.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
  servicenetworking.googleapis.com:
