---
billingDeptId: "90576"
project:
  name: doms-sec-vault-lle
  managed: true
  folderId: "882166644980"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90576"
    project-manager: manasa-ramayanam
    devops-lead: joe-vanhorn
    environment-type: lle
    line-of-business: sec
    project-requestor: rich-holcombe
serviceAPIs:
  cloudasset.googleapis.com:
  bigquery.googleapis.com:
  bigquerystorage.googleapis.com:
  cloudkms.googleapis.com:
  cloudresourcemanager.googleapis.com:
  compute.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  pubsub.googleapis.com:
  stackdriver.googleapis.com:
  storage-api.googleapis.com:
  storage-component.googleapis.com:
  iam.googleapis.com:
  privateca.googleapis.com:
  iap.googleapis.com:
