---
billingDeptId: "90546" # The billing ID can be challenging to find, when in doubt ask your mananger. This will evetually be abstracted away.
project:
  name: doms-infra-win-ad-prd # This vaule is the project name and ID, it must be unique. The format is doms-domain-productgroup-productline-environment The productline is optional
  deletionProtect: true
  managed: true # this value allows KCC to manage the resource.
  folderId: "980929416788" # The folder ID determines the placment in the GCP Organization higharchey. The folder IDs are in the docs here: https://gitlab.com/doms/infra/platform_enablement/cloud-config/gcp-config/-/blob/main/docs/Projects/Project_Jump_Start_Guide.md#netx-project-folder-id-lookup-table
  billingAccount: "00C36A-CD0BDB-E543D0" # This is always the same and will be abstracted in the future
  labels: # Labels are part of the project metadata and are used for such things as billing, contact info, etc. Some are required.
    billing-dept-id: "90546" # Again the illusuve billing ID
    project-manager: jordon-jochum # This is the product mananger, the field will get updated eventually
    devops-lead: steve-panozzo # This will change to engineering-lead, this is the main technical point of contact.
    environment-type: prd # sbx=sandbox lle=non-prod prd=prod This should match the environment type of the project name.
    line-of-business: win
    project-requestor: steve
    # optional-label: value # Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed. International characters are allowed.
serviceAPIs: # These are the Google Cloud servcies that your will need, enable these when you need to use additional APIs.
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
