---
project:
  labels:
    billing-dept-id: '90513'
    environment-type: prd
    devops-lead: rich-holcombe
    project-manager: kelly-neumann
    line-of-business: sec
    project-requestor: rich-holcombe
  name: doms-infosec-prd
  managed: true
  deletionProtect: true
  folderId: 726913521927
  billingAccount: 00C36A-CD0BDB-E543D0
# For lookup table of folder IDs: https://gitlab.com/doms/infra/platform_enablement/cloud-config/gcp-config/-/blob/main/docs/Projects/Project_Jump_Start_Guide.md#netx-project-folder-id-lookup-table
