---
billingDeptId: 90577
project:
  name: kohls-seed-xpn-lle
  managed: true
  deletionProtect: true
  folderId: 778811484176
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90577
    project-manager: matt-ploetz
    devops-lead: todd-winter
    environment-type: lle
    line-of-business: seed
    project-requestor: neha-racharla
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
projectSharing:
- kohls-scf-lle
- kohls-cx-scf-instaclustr-lle
