---
billingDeptId: "90538"
project:
  name: doms-etcc-aacs-lle
  deletionProtect: true
  managed: true
  folderId: "859213288423"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90538"
    project-manager: carlson-quick
    devops-lead: mark-battaglia
    environment-type: lle
    line-of-business: etcc
    project-requestor: vincent-gnanamuthu
serviceAPIs:
  bigquery.googleapis.com:
  bigquerydatatransfer.googleapis.com:
  bigquerystorage.googleapis.com:
  compute.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
