---
billingDeptId: "90527"
project:
  name: doms-eta-hr-prd
  deletionProtect: true
  managed: true
  folderId: "347385755519"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90527"
    project-manager: kevin-catlin
    devops-lead: ramkumar-sivanandam
    environment-type: prd
    line-of-business: hcm
    project-requestor: krysten-leroy
