---
billingDeptId: 90505
project:
  name: doms-ecom-xpn-prd
  managed: true
  deletionProtect: true
  folderId: 970875009337
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90505
    project-manager: jame-morales
    devops-lead: ford-mcdonald
    environment-type: prd
    line-of-business: ecom
    project-requestor: joshy-madhavan
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
