---
project:
  name: doms-cx-sremgmt-prd
  managed: true
  folderId: "259606834999"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90512"
    project-manager: thilaga-kumaran-srinivasan
    devops-lead: sachin-pathak
    environment-type: prd
    line-of-business: cx
    project-requestor: srinivasa-rao-yedla

serviceAPIs:
  compute.googleapis.com:
  cloudresourcemanager.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
  networkmanagement.googleapis.com:
  networktopology.googleapis.com:
