---
project:
  name: doms-vmo-lle
  managed: true
  folderId: "345254712059"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90528"
    project-manager: cindy-anderson
    devops-lead: sherri-luckett
    environment-type: lle
    line-of-business: vmo
    lob: vmo
    project-requestor: tom-huelhorst
serviceAPIs:
  bigquery.googleapis.com:
  cloudasset.googleapis.com:
  logging.googleapis.com:
