---
project:
  name: kohls-bda-dse-lle
  managed: true
  folderId: "124759181101" # CCX
  billingAccount: 00C36A-CD0BDB-E543D0
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90588"
    project-manager: "antonia-doneva"
    devops-lead: "venkata-subba-reddy-yerragudi"
    environment-type: lle
    line-of-business: dse
    lob: dse
    project-requestor: "xiaobing-luo"
