---
project:
  name: domsqa-cpa-inspec
  managed: false
  folderId: "749510905054"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90586"
    project-requestor: mark-doll
    project-manager: steve-pethan
    devops-lead: mark-doll
    line-of-business: cpe
    environment-type: hle
