---
project:
  name: kohls-bda-mkt-prd
  managed: true
  folderId: "217021366087" # merch-mkt-analytics
  billingAccount: 00C36A-CD0BDB-E543D0
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90585"
    project-manager: "paul-tunnicliff"
    devops-lead: "nutan-gandi"
    environment-type: prd
    line-of-business: dp
    lob: mkt
    project-requestor: "nutan-gandi"
