---
billingDeptId: "90522"
project:
  name: kohls-eta-credit-prd
  deletionProtect: true
  managed: true
  folderId: "155882274299"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90522"
    project-manager: nicki-kaszuba
    devops-lead: nilab-mousa
    environment-type: prd
    line-of-business: eta
    project-requestor: nilab-mousa
# For lookup table of folder IDs: https://gitlab.com/kohls/infra/platform_enablement/cloud-config/gcp-config/-/blob/main/docs/Projects/Project_Jump_Start_Guide.md#netx-project-folder-id-lookup-table
