---
billingDeptId: "90586"
projectSharing:
- kohls-cpe-e2edemo-lle
project:
  name: kohls-cpe-e2edemoxpn-lle
  managed: true
  folderId: "778811484176"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_), lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90586"
    project-manager: charles-anthony
    devops-lead: james-barber
    environment-type: lle
    line-of-business: cpe
    project-requestor: charles-anthony
serviceAPIs:
  compute.googleapis.com:
  oslogin.googleapis.com:
  cloudresourcemanager.googleapis.com:
  storage-component.googleapis.com:
  storage-api.googleapis.com:
  stackdriver.googleapis.com:
  logging.googleapis.com:
  monitoring.googleapis.com:
  cloudasset.googleapis.com:
