---
project:
  name: doms-infra-pie-lle
  managed: true
  folderId: "345254712059"
  billingAccount: "00C36A-CD0BDB-E543D0"
  labels:
    billing-dept-id: "90528"
    project-requestor: "katie-casey"
    project-manager: "katie-casey"
    devops-lead: "katie-casey"
    line-of-business: infra
    environment-type: nonprd
