---
billingDeptId: 90514
project:
  name: doms-merch-xpn-prd
  managed: true
  deletionProtect: true
  folderId: "217021366087"
  billingAccount: 00C36A-CD0BDB-E543D0
  labels:
    billing-dept-id: 90514
    project-manager: joel-schrock
    devops-lead: griffin-strain
    environment-type: prd
    line-of-business: merch
    project-requestor: joel-schrock
serviceAPIs:
  cloudresourcemanager.googleapis.com:
  cloudasset.googleapis.com:
  compute.googleapis.com:
  monitoring.googleapis.com:
  networkmanagement.googleapis.com:
  storage-api.googleapis.com:
projectSharing:
- doms-merch-pl-prd
- doms-merch-item-prd
- doms-merch-ps-prd
