apiVersion: v1
kind: PersistentVolume
metadata:
  name: l4-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
