---
billingDeptId: "90546"
project:
  name: doms-multitenant-xpn-lle
  managed: false
  folderId: "778811484176"
  billingAccount: "00C36A-CD0BDB-E543D0"
  # Only hyphens (-), underscores (_),lowercase characters,
  # and numbers are allowed as characters in labels
  labels:
    billing-dept-id: "90546"
    project-manager: david-hearn
    devops-lead: placeholder
    environment-type: lle
    line-of-business: infra
    project-requestor: patrick-kass
